const ActionTypes = {
   SET_USER: "SET_USER",
   REMOVE_USER: "REMOVE_USER",
   GET_QUESTIONS_AGE_WISE: "GET_QUESIONS_AGE_WISE",
   CURRENT_QUESTION: "CURRENT_QUESTION",
   QUESTIONS_ANSWERED: "QUESTIONS_ANSWERED"
}

export default ActionTypes